oc_platform_home:
    path:    /platform
    defaults:
        _controller: OCPlatformBundle:Advert:index
    
oc_platform_view:
    path:    /platform/advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
        
oc_platform_view_slug:
    path:    /platform/advert/{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml
oc_platform_add:
    path:    /platform/add
    defaults:
        _controller: OCPlatformBundle:Advert:add
        